//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microblog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Messages()
        {
            this.Collections = new HashSet<Collections>();
            this.Comments = new HashSet<Comments>();
            this.Transpond = new HashSet<Transpond>();
        }
    
        public int messages_id { get; set; }
        public Nullable<int> messagesType_id { get; set; }
        public string messages_info { get; set; }
        public Nullable<System.DateTime> messages_time { get; set; }
        public Nullable<int> messages_collectnum { get; set; }
        public Nullable<int> messages_commentnum { get; set; }
        public Nullable<int> messages_transpondnum { get; set; }
        public Nullable<int> messages_readnum { get; set; }
        public string resources_url { get; set; }
        public int user_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Collections> Collections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comments> Comments { get; set; }
        public virtual MessagesType MessagesType { get; set; }
        public virtual Users Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transpond> Transpond { get; set; }
    }
}
