//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microblog.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MicroblogDBEntities : DbContext
    {
        public MicroblogDBEntities()
            : base("name=MicroblogDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Collections> Collections { get; set; }
        public virtual DbSet<Comments> Comments { get; set; }
        public virtual DbSet<FriendGroup> FriendGroup { get; set; }
        public virtual DbSet<Messages> Messages { get; set; }
        public virtual DbSet<MessagesType> MessagesType { get; set; }
        public virtual DbSet<Relation> Relation { get; set; }
        public virtual DbSet<Transpond> Transpond { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Userinfo> Userinfo { get; set; }
    }
}
