//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microblog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transpond
    {
        public int transpond_id { get; set; }
        public int messages_id { get; set; }
        public int transpond_users_id { get; set; }
        public Nullable<System.DateTime> transpond_betime { get; set; }
        public string transpond_info { get; set; }
    
        public virtual Messages Messages { get; set; }
        public virtual Users Users { get; set; }
    }
}
