//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace Microblog.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Userinfo
    {
        public string userinfo_realname { get; set; }
        public string userinfo_address { get; set; }
        public string userinfo_sex { get; set; }
        public string userinfo_feeling { get; set; }
        public Nullable<System.DateTime> userinfo_birthday { get; set; }
        public string userinfo_bloodtype { get; set; }
        public string userinfo_intro { get; set; }
        [RegularExpression(@"^[a-zA-Z0-9_-]+@[a-zA-Z0-9_-]+(\.[a-zA-Z0-9_-]+)+$", ErrorMessage = "请输入正确邮箱格式")]
        public string userinfo_email { get; set; }

        [RegularExpression(@"[1-9] [0-9]{4,}", ErrorMessage = "请输入正确格式QQ号")]
        public string userinfo_qqnumber { get; set; }
        public string userinfo_profession { get; set; }
        public string userinfo_tag { get; set; }
        public int user_id { get; set; }
        public string user_headphoto { get; set; }
        public string resources_themeurl { get; set; }

        public virtual Users Users { get; set; }
    }
}
